title: cauchy's blog
author: GitHub User
email: 
description: > # this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: ξ的个人博客
  tagline: 欢迎，这里是ξ的个人博客，会不定时更新ξ个人创作的故事等内容。 qq：981130268 哔哩哔哩uid：23027694 微博：E_Blood<a target="_blank" 
  href="http://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=3L_9qb_0pbupnK2t8r_zsQ" style="text-decoration:none;">
  <img src="http://rescdn.qqmail.com/zh_CN/htmledition/images/function/qm_open/ico_mailme_22.png"/></a>
  date_format: "%b %-d, %Y"
  style: blue
  showNav: false
  showPicker: false
  # generate social links in footer
  social_links:
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
theme: jekyll-theme-slate
remote_theme: thelehhman/texture
theme: texture
